version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    expose:
      - "5000"
    environment:
      DB_HOST: database-1.cv6m8aiiqflt.eu-north-1.rds.amazonaws.com
      DB_USER: admin
      DB_PASS: 8590251179
      DB_NAME: devopsdb

